### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by Carrot-17** [moelty-net/tshock-ui#1]
I don't konw how to get the username and password?

**Comment by baobao1270** [comment]
The password is configurated in TShock. Username and password will be passed to TShock REST API.

Please modify your `config.json`:
```
"EnableTokenEndpointAuthentication": true,
  "ApplicationRestTokens": {
          "p@ssw0rd": {
                  "Username": "yourusername",
                  "UserGroupName": "superadmin"
          }
  }
```

Please leave `UserGroupName` unchanged, which is `superadmin`. Or you won't have permission to restart or stop the server.

For more details, please see:
 - https://tshock.readme.io/reference/rest-api-endpoints
 - https://tshock.readme.io/docs/config-settings#rest-api-settings

**Comment by baobao1270** [comment]
Please provide more details. You can use the dev tool (press <kbd>F12</kbd>) to get the error detail.
